"""Compatibility entry point. cz-v1 uses the unified, annotation-free baseline.

Historical main-branch results were generated by a different policy and must not
be pooled with cz-v1 ablations.
"""

from agent.baseline_agent import BaselineAgent
from agent.react_agent import canonical_action


def is_valid_action(action, available_actions):
    return canonical_action(action, available_actions) is not None


class NoMemoryReActAgent(BaselineAgent):
    """Legacy name; memory is task-local, with no cross-task persistent memory."""
